services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "python config_extension.py && xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' python main.py"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    networks:
      - app-network
    restart: always
    deploy:
      mode: replicated
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  app-network:
    driver: bridge
