services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "python config_extension.py && python main.py"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge
