# Remove or comment out the version line if it exists
# version: "3.8"  

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "python config_extension.py && python main.py"
